---
name: Sync the template repository

on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Queue
      uses: ahmadnassri/action-workflow-queue@v1.1
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Sync
      uses: ahmadnassri/action-template-repository-sync@v2.3.4
      with:
        github-token: ${{ secrets.GH_TOKEN }}
